import { LegacyJobApplication, LegacyInterview, LegacyContact } from '../types/jobs';

export const mockJobApplications: LegacyJobApplication[] = [
  {
    id: '1',
    title: 'Senior Product Manager',
    company: 'Google',
    location: 'Mountain View, CA',
    workMode: 'hybrid',
    salaryRange: {
      min: 180000,
      max: 250000,
      currency: 'USD',
    },
    jobUrl: 'https://careers.google.com/jobs/12345',
    companyWebsite: 'https://google.com',
    description: 'Lead product strategy for Google Cloud AI products...',
    status: 'interviewing',
    priority: 'high',
    appliedDate: '2025-11-01',
    notes: 'Strong referral from Jane. Focus on ML/AI product experience.',
    createdAt: '2025-10-28',
    updatedAt: '2025-11-10',
  },
  {
    id: '2',
    title: 'Product Manager, Growth',
    company: 'Stripe',
    location: 'San Francisco, CA',
    workMode: 'hybrid',
    salaryRange: {
      min: 170000,
      max: 230000,
      currency: 'USD',
    },
    jobUrl: 'https://stripe.com/jobs/listing/pm-growth',
    companyWebsite: 'https://stripe.com',
    description: 'Drive growth initiatives for Stripe\'s core payments platform...',
    status: 'applied',
    priority: 'high',
    appliedDate: '2025-11-05',
    deadline: '2025-11-20',
    notes: 'Great culture fit. Emphasize fintech experience.',
    createdAt: '2025-11-03',
    updatedAt: '2025-11-05',
  },
  {
    id: '3',
    title: 'Principal Product Manager',
    company: 'Amazon',
    location: 'Seattle, WA',
    workMode: 'onsite',
    salaryRange: {
      min: 200000,
      max: 280000,
      currency: 'USD',
    },
    jobUrl: 'https://amazon.jobs/en/jobs/2345678',
    status: 'screening',
    priority: 'medium',
    appliedDate: '2025-10-25',
    notes: 'Initial recruiter call scheduled. Review leadership principles.',
    createdAt: '2025-10-20',
    updatedAt: '2025-11-08',
  },
  {
    id: '4',
    title: 'Product Manager, Platform',
    company: 'Notion',
    location: 'San Francisco, CA',
    workMode: 'remote',
    salaryRange: {
      min: 160000,
      max: 210000,
      currency: 'USD',
    },
    status: 'wishlist',
    priority: 'high',
    notes: 'Dream company. Need to find referral.',
    createdAt: '2025-11-10',
    updatedAt: '2025-11-10',
  },
  {
    id: '5',
    title: 'Senior PM, AI Products',
    company: 'OpenAI',
    location: 'San Francisco, CA',
    workMode: 'hybrid',
    salaryRange: {
      min: 190000,
      max: 270000,
      currency: 'USD',
    },
    jobUrl: 'https://openai.com/careers/senior-pm',
    status: 'offer',
    priority: 'high',
    appliedDate: '2025-10-15',
    notes: 'Offer received! Review by Nov 18th. Great team and mission.',
    createdAt: '2025-10-10',
    updatedAt: '2025-11-12',
  },
  {
    id: '6',
    title: 'Product Manager',
    company: 'Meta',
    location: 'Menlo Park, CA',
    workMode: 'hybrid',
    status: 'rejected',
    priority: 'medium',
    appliedDate: '2025-09-15',
    notes: 'Rejected after final round. Feedback: Need more cross-functional leadership examples.',
    createdAt: '2025-09-10',
    updatedAt: '2025-10-20',
  },
];

export const mockInterviews: LegacyInterview[] = [
  {
    id: 'int-1',
    applicationId: '1',
    title: 'Technical Deep Dive',
    type: 'technical',
    status: 'scheduled',
    scheduledFor: '2025-11-18T14:00:00',
    duration: 60,
    meetingLink: 'https://meet.google.com/abc-defg-hij',
    interviewers: ['Sarah Chen - Engineering Manager', 'Mike Johnson - Senior Engineer'],
    prepNotes: 'Review system design patterns, focus on ML infrastructure scaling',
    createdAt: '2025-11-10',
  },
  {
    id: 'int-2',
    applicationId: '1',
    title: 'Recruiter Phone Screen',
    type: 'recruiter_screen',
    status: 'completed',
    scheduledFor: '2025-11-05T10:00:00',
    duration: 30,
    feedback: 'Great conversation. Moving forward to technical rounds.',
    createdAt: '2025-11-01',
  },
  {
    id: 'int-3',
    applicationId: '3',
    title: 'Bar Raiser Interview',
    type: 'behavioral',
    status: 'scheduled',
    scheduledFor: '2025-11-16T11:00:00',
    duration: 45,
    location: 'Amazon HQ, Seattle',
    prepNotes: 'Prepare STAR stories for all 16 leadership principles',
    createdAt: '2025-11-08',
  },
  {
    id: 'int-4',
    applicationId: '5',
    title: 'Final Round - Product Strategy',
    type: 'final',
    status: 'completed',
    scheduledFor: '2025-11-08T15:00:00',
    duration: 90,
    interviewers: ['CEO', 'VP Product', 'Head of AI'],
    feedback: 'Excellent discussion on AI product strategy. Offer extended!',
    createdAt: '2025-11-05',
  },
];

export const mockContacts: LegacyContact[] = [
  {
    id: 'cont-1',
    applicationId: '1',
    name: 'Jane Smith',
    title: 'Senior Product Manager',
    email: 'jane.smith@google.com',
    linkedinUrl: 'https://linkedin.com/in/janesmith',
    relationship: 'referral',
    lastContactDate: '2025-10-25',
    notes: 'Former colleague from startup. Provided strong referral.',
    interactions: [
      {
        id: 'int-1',
        date: '2025-10-25',
        type: 'coffee',
        summary: 'Coffee chat about Google culture and team',
        notes: 'Very helpful insights on the interview process',
      },
      {
        id: 'int-2',
        date: '2025-10-20',
        type: 'email',
        summary: 'Initial outreach for referral',
      },
    ],
    createdAt: '2025-10-20',
  },
  {
    id: 'cont-2',
    applicationId: '1',
    name: 'Robert Chen',
    title: 'Recruiting Lead',
    email: 'robert.chen@google.com',
    phone: '+1 (650) 555-0123',
    relationship: 'recruiter',
    lastContactDate: '2025-11-10',
    notes: 'Main point of contact. Very responsive.',
    interactions: [
      {
        id: 'int-3',
        date: '2025-11-10',
        type: 'email',
        summary: 'Technical interview scheduled',
      },
      {
        id: 'int-4',
        date: '2025-11-05',
        type: 'phone',
        summary: 'Phone screen - 30 min',
      },
    ],
    createdAt: '2025-11-01',
  },
  {
    id: 'cont-3',
    applicationId: '2',
    name: 'Emily Rodriguez',
    title: 'PM, Growth Team',
    linkedinUrl: 'https://linkedin.com/in/emilyrodriguez',
    relationship: 'team_member',
    lastContactDate: '2025-11-03',
    notes: 'Connected via LinkedIn. Interested in grabbing coffee.',
    interactions: [
      {
        id: 'int-5',
        date: '2025-11-03',
        type: 'linkedin',
        summary: 'Initial connection and message',
      },
    ],
    createdAt: '2025-11-03',
  },
];

export const mockCompanyResearch: Record<string, any> = {
  '1': {
    id: 'res-1',
    applicationId: '1',
    overview: 'Google is a global technology leader specializing in search, cloud computing, and AI.',
    culture: 'Data-driven, innovative, collaborative. Strong focus on impact and "10x thinking".',
    products: ['Google Search', 'Google Cloud', 'Gmail', 'Google Maps', 'Android'],
    techStack: ['C++', 'Java', 'Python', 'Go', 'TensorFlow'],
    recentNews: [
      {
        title: 'Google Cloud announces new AI capabilities',
        url: 'https://techcrunch.com/google-cloud-ai',
        date: '2025-11-01',
      },
      {
        title: 'Google expands Mountain View campus',
        url: 'https://news.google/campus-expansion',
        date: '2025-10-28',
      },
    ],
    interviewTips: 'Focus on analytical thinking, structured problem-solving, and demonstrating impact with metrics.',
    updatedAt: '2025-11-01',
  },
};

